name: Build Application

on:
  push:
    tags: ['v*']
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build and publish with dotnet
        run: dotnet publish -c Release
      - name: Install plugins
        run: |
          xcopy /s /E /I /Y /q "Attribulator.Plugins.ModScript\\bin\\x86\\Release\\net9.0-windows\\publish" "Attribulator.CLI\\bin\\x86\\Release\\net9.0-windows\\publish\\plugins\\Attribulator.Plugins.ModScript"
          xcopy /s /E /I /Y /q "Attribulator.Plugins.YAMLSupport\\bin\\x86\\Release\\net9.0-windows\\publish" "Attribulator.CLI\\bin\\x86\\Release\\net9.0-windows\\publish\\plugins\\Attribulator.Plugins.YAMLSupport"
          xcopy /s /E /I /Y /q "Attribulator.Plugins.SpeedProfiles\\bin\\x86\\Release\\net9.0-windows\\publish" "Attribulator.CLI\\bin\\x86\\Release\\net9.0-windows\\publish\\plugins\\Attribulator.Plugins.SpeedProfiles"
      - name: Add NativeLibrary.dll
        run: copy external/NativeLibrary.dll Attribulator.CLI/bin/x86/Release/net9.0-windows/publish/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_windows
          path: Attribulator.CLI/bin/x86/Release/net9.0-windows/publish
  upload-release:
    needs: [ build-windows ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release_windows
          path: release_windows

      - name: Make zip archives
        run: zip -r release_windows.zip release_windows

      - name: Create GitHub Release and upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ github.ref_name }}" \
            release_windows.zip \
            --title "${{ github.ref_name }}" \
            --notes "Generated by GitHub Actions" \
            --draft
