name: Build Application

on:
  push:
    tags: ['v*']
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build and publish Attribulator.UI
        run: dotnet publish Attribulator.UI/Attribulator.UI.csproj -c Release

      - name: Install plugins
        run: |
          xcopy /s /E /I /Y /q "Attribulator.Plugins.ModScript\\bin\\x86\\Release\\net9.0-windows\\publish" "Attribulator.UI\\bin\\Release\\net9.0-windows\\publish\\plugins\\Attribulator.Plugins.ModScript"
          xcopy /s /E /I /Y /q "Attribulator.Plugins.YAMLSupport\\bin\\x86\\Release\\net9.0-windows\\publish" "Attribulator.UI\\bin\\Release\\net9.0-windows\\publish\\plugins\\Attribulator.Plugins.YAMLSupport"
          xcopy /s /E /I /Y /q "Attribulator.Plugins.SpeedProfiles\\bin\\x86\\Release\\net9.0-windows\\publish" "Attribulator.UI\\bin\\Release\\net9.0-windows\\publish\\plugins\\Attribulator.Plugins.SpeedProfiles"

      - name: Upload UI artifact
        uses: actions/upload-artifact@v4
        with:
          name: release_ui
          path: Attribulator.UI/bin/Release/net9.0-windows/publish
  
  upload-release:
    needs: [ build-windows ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: release_windows
          path: release_windows

      - uses: actions/download-artifact@v4
        with:
          name: release_ui
          path: release_ui

      - name: Zip artifacts
        run: |
          zip -r Attribulator.UI.zip release_ui

      - name: Create release if missing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view "${{ github.ref_name }}" || \
          gh release create "${{ github.ref_name }}" \
            --title "${{ github.ref_name }}" \
            --notes "Generated by GitHub Actions" \
            --draft

      - name: Upload assets (replace if exist)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            Attribulator.UI.zip \
            --clobber
  